import type { HeroConfig } from '@autocard/shared';

export const HEROES: HeroConfig[] = [
  {
    heroId: 'dooley',
    name: '杜利',
    description: '连锁触发型机器人。通过 Core 核心物品驱动链式反应，燃烧/冻结协同爆发。',
    baseHp: 100,
    hpPerLevel: 10,
    startingGold: 8,
    startingItems: ['皂沫中士'],
    skillPool: [],
  },
  {
    heroId: 'jules',
    name: '朱尔斯',
    description: '欢乐型/另类胜利。通过 Joy 欢乐机制让对手"太开心而不战"，护盾暴击兼顾。',
    baseHp: 90,
    hpPerLevel: 9,
    startingGold: 8,
    startingItems: ['巴努叶'],
    skillPool: [],
  },
  {
    heroId: 'mak',
    name: '麦克',
    description: '药剂/毒/燃烧型。通过 Potion 药剂和 Reagent 试剂转化，堆叠持续伤害。',
    baseHp: 95,
    hpPerLevel: 9,
    startingGold: 8,
    startingItems: ['翡翠'],
    skillPool: [],
  },
  {
    heroId: 'pygmalien',
    name: '皮格马利翁',
    description: '坦克/经济型。护盾治疗滚雪球，Property 房产物品产金，生命值可无限堆叠。',
    baseHp: 120,
    hpPerLevel: 12,
    startingGold: 10,
    startingItems: ['没药'],
    skillPool: [],
  },
  {
    heroId: 'stelle',
    name: '斯泰尔',
    description: '机甲/载具型。Vehicle 载具驱动高暴击与护盾，工具联动燃烧攻击。',
    baseHp: 100,
    hpPerLevel: 10,
    startingGold: 8,
    startingItems: ['蒸汽汤勺'],
    skillPool: [],
  },
  {
    heroId: 'vanessa',
    name: '瓦内莎',
    description: '武器爆发/水生毒控双路线。多武器暴力或水生减速+毒素组合，新手友好。',
    baseHp: 95,
    hpPerLevel: 9,
    startingGold: 8,
    startingItems: ['毒液'],
    skillPool: [],
  },
];
