import type { ItemConfig } from '@autocard/shared';

export const ITEMS: ItemConfig[] = [
  // ===== 战士初始 & 相关 =====
  {
    itemId: 'iron_sword',
    name: '铁剑',
    description: '基础近战武器，造成直接伤害',
    size: 1,
    baseTier: 'bronze',
    price: 3,
    cooldown: 2,
    ports: [{ category: 'output', type: 'damage', value: 8 }],
    targetRule: { kind: 'self' },
    tags: ['weapon', 'melee'],
    sourceHero: 'warrior',
  },
  {
    itemId: 'war_axe',
    name: '战斧',
    description: '大型武器，高伤害长冷却',
    size: 2,
    baseTier: 'bronze',
    price: 5,
    cooldown: 4,
    ports: [{ category: 'output', type: 'damage', value: 18 }],
    targetRule: { kind: 'self' },
    tags: ['weapon', 'melee'],
    sourceHero: 'warrior',
  },
  {
    itemId: 'battle_horn',
    name: '战号角',
    description: '为相邻武器提供加速',
    size: 1,
    baseTier: 'bronze',
    price: 4,
    cooldown: 3,
    ports: [{ category: 'operational', type: 'haste', value: 1 }],
    targetRule: { kind: 'adjacent' },
    tags: ['accessory'],
    sourceHero: 'warrior',
  },
  {
    itemId: 'shield_plate',
    name: '钢盾',
    description: '提供护盾值',
    size: 1,
    baseTier: 'bronze',
    price: 3,
    cooldown: 3,
    ports: [{ category: 'defense', type: 'shield', value: 10 }],
    targetRule: { kind: 'self' },
    tags: ['armor'],
    sourceHero: 'warrior',
  },

  // ===== 法师初始 & 相关 =====
  {
    itemId: 'fire_wand',
    name: '火焰法杖',
    description: '造成灼烧效果',
    size: 1,
    baseTier: 'bronze',
    price: 3,
    cooldown: 3,
    ports: [{ category: 'output', type: 'burn', value: 6 }],
    targetRule: { kind: 'self' },
    tags: ['weapon', 'magic'],
    sourceHero: 'mage',
  },
  {
    itemId: 'frost_orb',
    name: '冰霜宝珠',
    description: '冰冻敌方，降低行动',
    size: 1,
    baseTier: 'bronze',
    price: 4,
    cooldown: 4,
    ports: [{ category: 'operational', type: 'freeze', value: 2 }],
    targetRule: { kind: 'self' },
    tags: ['accessory', 'magic'],
    sourceHero: 'mage',
  },
  {
    itemId: 'arcane_tome',
    name: '奥术典籍',
    description: '为最左侧法术装备充能',
    size: 2,
    baseTier: 'silver',
    price: 8,
    cooldown: 2,
    ports: [{ category: 'operational', type: 'charge', value: 2 }],
    targetRule: { kind: 'leftmost' },
    tags: ['accessory', 'magic'],
    sourceHero: 'mage',
  },
  {
    itemId: 'inferno_staff',
    name: '地狱法杖',
    description: '大型法杖，高灼烧输出',
    size: 3,
    baseTier: 'silver',
    price: 12,
    cooldown: 5,
    ports: [{ category: 'output', type: 'burn', value: 25 }],
    targetRule: { kind: 'self' },
    tags: ['weapon', 'magic'],
    sourceHero: 'mage',
  },

  // ===== 盗贼初始 & 相关 =====
  {
    itemId: 'poison_dagger',
    name: '淬毒匕首',
    description: '快速攻击，叠加剧毒',
    size: 1,
    baseTier: 'bronze',
    price: 3,
    cooldown: 1,
    ports: [{ category: 'output', type: 'poison', value: 4 }],
    targetRule: { kind: 'self' },
    tags: ['weapon', 'melee'],
    sourceHero: 'rogue',
  },
  {
    itemId: 'swift_boots',
    name: '疾行靴',
    description: '为所有装备提供加速',
    size: 1,
    baseTier: 'bronze',
    price: 5,
    cooldown: 3,
    ports: [{ category: 'operational', type: 'haste', value: 1 }],
    targetRule: { kind: 'all' },
    tags: ['accessory'],
    sourceHero: 'rogue',
  },
  {
    itemId: 'venom_vial',
    name: '剧毒药瓶',
    description: '为相邻武器附加剧毒',
    size: 1,
    baseTier: 'bronze',
    price: 4,
    cooldown: 2,
    ports: [{ category: 'output', type: 'poison', value: 6 }],
    targetRule: { kind: 'adjacent' },
    tags: ['consumable'],
    sourceHero: 'rogue',
  },
  {
    itemId: 'shadow_cloak',
    name: '暗影斗篷',
    description: '减速敌方并提供闪避',
    size: 2,
    baseTier: 'silver',
    price: 7,
    cooldown: 4,
    ports: [{ category: 'operational', type: 'slow', value: 2 }],
    targetRule: { kind: 'self' },
    tags: ['armor'],
    sourceHero: 'rogue',
  },

  // ===== 牧师初始 & 相关 =====
  {
    itemId: 'holy_staff',
    name: '圣光法杖',
    description: '治疗自身',
    size: 1,
    baseTier: 'bronze',
    price: 3,
    cooldown: 3,
    ports: [{ category: 'defense', type: 'heal', value: 10 }],
    targetRule: { kind: 'self' },
    tags: ['weapon', 'magic'],
    sourceHero: 'priest',
  },
  {
    itemId: 'prayer_beads',
    name: '祈祷念珠',
    description: '为相邻装备充能',
    size: 1,
    baseTier: 'bronze',
    price: 4,
    cooldown: 2,
    ports: [{ category: 'operational', type: 'charge', value: 1 }],
    targetRule: { kind: 'adjacent' },
    tags: ['accessory'],
    sourceHero: 'priest',
  },
  {
    itemId: 'divine_robe',
    name: '神圣长袍',
    description: '提供大量护盾',
    size: 2,
    baseTier: 'silver',
    price: 8,
    cooldown: 4,
    ports: [{ category: 'defense', type: 'shield', value: 20 }],
    targetRule: { kind: 'self' },
    tags: ['armor'],
    sourceHero: 'priest',
  },
  {
    itemId: 'smite_cross',
    name: '惩击十字',
    description: '神圣伤害，牧师的输出手段',
    size: 1,
    baseTier: 'bronze',
    price: 4,
    cooldown: 3,
    ports: [{ category: 'output', type: 'damage', value: 7 }],
    targetRule: { kind: 'self' },
    tags: ['weapon', 'magic'],
    sourceHero: 'priest',
  },

  // ===== 通用（无职业限制） =====
  {
    itemId: 'health_potion',
    name: '生命药水',
    description: '恢复生命值',
    size: 1,
    baseTier: 'bronze',
    price: 2,
    cooldown: 5,
    ports: [{ category: 'defense', type: 'heal', value: 15 }],
    targetRule: { kind: 'self' },
    tags: ['consumable'],
  },
  {
    itemId: 'energy_crystal',
    name: '能量水晶',
    description: '为最右侧装备充能',
    size: 1,
    baseTier: 'bronze',
    price: 3,
    cooldown: 2,
    ports: [{ category: 'operational', type: 'charge', value: 1 }],
    targetRule: { kind: 'rightmost' },
    tags: ['accessory'],
  },
  {
    itemId: 'thorns_ring',
    name: '荆棘之戒',
    description: '反弹伤害给敌方',
    size: 1,
    baseTier: 'bronze',
    price: 4,
    cooldown: 3,
    ports: [{ category: 'output', type: 'damage', value: 5 }],
    targetRule: { kind: 'self' },
    tags: ['accessory'],
  },
  {
    itemId: 'giants_club',
    name: '巨人棒',
    description: '超大型武器，极高伤害',
    size: 3,
    baseTier: 'silver',
    price: 15,
    cooldown: 6,
    ports: [{ category: 'output', type: 'damage', value: 35 }],
    targetRule: { kind: 'self' },
    tags: ['weapon', 'melee'],
  },
];

export const ITEMS_MAP = new Map(ITEMS.map(i => [i.itemId, i]));
